### ISSUE TITLE
Starbase setup error

### ISSUE THREAD

**Issue by emilva** [JupiterOne/starbase#50]
Hi team,

Trying to follow the instructions in the README, but keep getting this error when I run starbase setup. It is likely related to git, but I cannot find any info in the readme about how you configure git. The git command works fine in my shell outside of `starbase setup`

``` 
yarn starbase setup
yarn run v1.22.17
$ ts-node ./src/index.ts setup
[Error: authentication required but no callback set] {
  errno: -1,
  errorFunction: 'Clone.clone'
}
error Command failed with exit code 1.
```

**Comment by ceelias** [comment]
Hey @emilva 👋 

Thanks for posting this issue. The following information would help us narrow down on the issue you are seeing.

* How do you have git configured on your machine, are you using git with `ssh` keys or are you authenticating with `username/password`?
* What operating system are you using?
* Can you post the `config.yaml` you are attempting to use here

**Comment by emilva** [comment]
Hello!

I am using ssh on os x. 

The config.yaml is as follows, but when I read the gitRemoteUrl now I realize that it might help to change it to `git@github.com:/` instead of the `https://` thing :D 

```
integrations:
  - name: graph-google-cloud
    instanceId: testInstanceId
    directory: ./.integrations/graph-google-cloud
    gitRemoteUrl: https://github.com/JupiterOne/graph-google-cloud.git
    config:
      SERVICE_ACCOUNT_KEY_FILE: 'filename.json'
      PROJECT_ID: 'projectid'
      ORGANIZATION_ID: 'orgid'
      CONFIGURE_ORGANIZATION_PROJECTS: false
storage:
  engine: neo4j
  config: 
    username: neo4j
    password: devpass
    uri: bolt://localhost:7687
```
