### ISSUE TITLE
Support JupiterOne storage engine target 

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/starbase#60]
# Description

Currently we support uploading data collected by Starbase to Neo4j. It would be great if Starbase users could alternatively support JupiterOne as a storage target. This would allow JupiterOne users to run multiple integrations easily using a single tool.

## Proposal

JupiterOne storage engine configuration may resemble the following:

```ts
type JupiterOneStorageEngineConfig = {
  /**
  * The JupiterOne API key to authenticate with
  */
  apiKey: string;
  /**
  * The JupiterOne account ID to target
  */
  accountId: string;
  /**
  * If provided this option specifies which base URL to use for synchronization (default: `https://api.us.jupiterone.io`)
  */
  apiBaseUrl?: string;
};
```

```yaml
storage:
  engine: jupiterone
  config:
    apiKey: "..."
    accountId: "..."
    apiBaseUrl: "https://api.us.jupiterone.io"
```
