### ISSUE TITLE
Add support for specifying which Neo4j database to push data to

### ISSUE THREAD

**Issue by adam-in-ict** [JupiterOne/starbase#77]
The enterprise version of Neo4j allows for multiple databases hosted on a single Neo4j server.  Adding an optional configuration value to specify the database to push to could be beneficial.  

The storage section for a Neo4j configuration could look something like this:

```yml
storage:
  engine: neo4j
  config:
    username:<username>
    password:<password>
    uri: bolt:<uri>
    database: neo4j
```

We would need to decide how to handle errors if a user tried to specify a database name while running the community edition which does not allow multiple databases.  One option would be to query the database initially using the `dbms.components()` call to get the `edition` and only allow a database to be specified when it is enterprise.
